name: CES Simulator CI

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - 'server/**'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'
      - 'server/**'

jobs:
  build-client:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd client && npm install
      - name: Build project
        run: cd client && npm run build

  test-server
